# Stage 1: NVIDIA Base
FROM nvidia/cuda:11.2.2-runtime-ubuntu20.04 AS nvidia-base

# Install necessary packages
RUN apt-get update && apt-get install -y \
    gdb \
    xvfb \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libgl1-mesa-dri \
    libglu1-mesa \
    freeglut3-dev \
    mesa-utils \
    wget \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Set environment variables
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility,video
